name: CI & Docker Publish

on:
  push:
    branches:
      - master

jobs:
   build-and-push:
    runs-on: ubuntu-latest
#############Most important for permission in last step################################
   # Need to add these permissions for id-token (GCP) and contents (GitHub tags)
    permissions:
     contents: 'write'  # Changed from 'read' to 'write' to allow creating tags
     id-token: 'write'
#############Most important for permission in last step################################
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Bump version and push tag    #get the version from tag or generate a new one
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1  # use fix, feat, feat! while committing to bump the version. chore, docs, style, refactor, perf, test will not bump the version.
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: patch
        dry_run: false # Safety check, set to true to test without pushing changes

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.315  # Specify the .NET version

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish_output

    - name: Build Docker image
      # Use git tag as version (only if new tag was created)
      if: steps.tag_version.outputs.new_tag != ''
      run: docker build -t eaglepop/mvck8stest:${{ steps.tag_version.outputs.new_tag }} .
      # run: docker build -t eaglepop/mvck8stest:latest .

    - name: Log in to Docker Hub
      if: steps.tag_version.outputs.new_tag != ''
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image 
      # Use git tag as version (only if new tag was created)
      if: steps.tag_version.outputs.new_tag != ''
      run: docker push eaglepop/mvck8stest:${{ steps.tag_version.outputs.new_tag }} 
      # run: docker push eaglepop/mvck8stest:latest

#######################本地測試K8s################################
    # - name: Setup Kubeconfig
    #   run: |
    #     mkdir -p $HOME/.kube
    #     echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
    #     chmod 600 $HOME/.kube/config

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/
    #     kubectl rollout restart deployment mvc-deployment -n dev
#######################本地測試K8s################################

#######################JSON key###################################
    #   # 授權給 GCP（取代 kubeconfig）
    # - name: Auth to GCP
    #   uses: google-github-actions/auth@v2
    #   with:
    #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # # 取得 GKE kubeconfig 並寫入 ~/.kube/config
    # - name: Get GKE credentials
    #   uses: google-github-actions/get-gke-credentials@v2
    #   with:
    #     cluster_name: mvck8stest-cluster
    #     location: asia-east1  # 換成你實際設定的區域
    #     project_id: mvck8stest # GCP 專案 ID
    # # 正式部署 YAML
    # - name: Deploy to GKE
    #   run: |
    #     kubectl apply -f k8s/
    #     kubectl rollout restart deployment mvc-deployment -n dev
#######################JSON key###################################

#######################WIF OIDC###################################
    - name: Authenticate to Google Cloud (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/1020520420634/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "mvck8stest@mvck8stest.iam.gserviceaccount.com"

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: mvck8stest-cluster
        location: asia-east1
        project_id: mvck8stest

    # Use git tag as version in kubectl set image command (only if new tag was created)
    - name: Deploy to GKE 
      if: steps.tag_version.outputs.new_tag != ''
      run: |
        kubectl apply -f k8s/ --validate=false || true
        sleep 5
        kubectl apply -f k8s/ 
        kubectl set image deployment/mvc-deployment mvc-container=eaglepop/mvck8stest:${{ steps.tag_version.outputs.new_tag }} -n dev  
        kubectl rollout restart deployment mvc-deployment -n dev
#######################WIF OIDC###################################


