name: CI & Docker Publish

on:
  push:
    branches:
      - master

jobs:
   build-and-push:
    runs-on: ubuntu-latest
#############Most important for permission in last step################################
   # Need to add these 3 lines to add "id-token" with the intended permissions.
    permissions:
     contents: 'read'
     id-token: 'write'
#############Most important for permission in last step################################
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.315  # Specify the .NET version

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish_output

    - name: Build Docker image
      run: docker build -t eaglepop/mvck8stest:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push eaglepop/mvck8stest:latest

#######################本地測試K8s################################
    # - name: Setup Kubeconfig
    #   run: |
    #     mkdir -p $HOME/.kube
    #     echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
    #     chmod 600 $HOME/.kube/config

    # - name: Deploy to Kubernetes
    #   run: |
    #     kubectl apply -f k8s/
    #     kubectl rollout restart deployment mvc-deployment -n dev
#######################本地測試K8s################################

#######################JSON key###################################
    #   # 授權給 GCP（取代 kubeconfig）
    # - name: Auth to GCP
    #   uses: google-github-actions/auth@v2
    #   with:
    #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # # 取得 GKE kubeconfig 並寫入 ~/.kube/config
    # - name: Get GKE credentials
    #   uses: google-github-actions/get-gke-credentials@v2
    #   with:
    #     cluster_name: mvck8stest-cluster
    #     location: asia-east1  # 換成你實際設定的區域
    #     project_id: mvck8stest # GCP 專案 ID
    # # 正式部署 YAML
    # - name: Deploy to GKE
    #   run: |
    #     kubectl apply -f k8s/
    #     kubectl rollout restart deployment mvc-deployment -n dev
#######################JSON key###################################

#######################WIF OIDC###################################
    - name: Authenticate to Google Cloud (WIF)
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/1020520420634/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "mvck8stest@mvck8stest.iam.gserviceaccount.com"

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: mvck8stest-cluster
        location: asia-east1
        project_id: mvck8stest

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/ --validate=false || true
        sleep 5
        kubectl apply -f k8s/
        kubectl rollout restart deployment mvc-deployment -n dev
#######################WIF OIDC###################################

